#!/usr/bin/env node
/**
 * migration/05-verify.mjs — the cutover gate for the Supabase region move
 * (ap-northeast-2 / Seoul  ->  eu-central-1 / Frankfurt).
 *
 * ─── READ-ONLY GUARANTEE ────────────────────────────────────────────────────
 * This script NEVER writes to either database. There is no INSERT, UPDATE,
 * DELETE, UPSERT, TRUNCATE, DDL, storage upload/remove or Management-API call
 * anywhere in it. Three independent layers enforce that:
 *
 *   1. Every statement it sends is a SELECT / WITH / SHOW, except three fixed
 *      session settings sent once per connection (see ReadOnlyConnection.
 *      connect). Those three are string literals in the source; nothing
 *      builds them and nothing else bypasses the guard.
 *   2. ReadOnlyConnection.query() refuses to send anything whose first keyword
 *      is not SELECT / WITH / SHOW, and refuses statement batching (';').
 *   3. Immediately after connecting, each session is put into
 *      `SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY` and the setting
 *      is read back, so PostgreSQL itself rejects a write with "cannot execute
 *      INSERT in a read-only transaction" even if layers 1 and 2 were defeated.
 *
 * It also never prints a secret. Connection strings are shown as
 * user@host:port/db with the password stripped.
 * The only file it may write is the optional --json report.
 *
 * ─── WHAT IT COMPARES ───────────────────────────────────────────────────────
 * (numbered as the run prints them)
 *   0. The table inventory parsed out of server/supa.js, against the 27 + 77
 *      this kit was written for. Drift is a WARN; the parsed list always wins.
 *   1. Sanity of the comparison itself: every collector ran, the SOURCE is not
 *      empty (two empty databases match on everything), engine versions agree,
 *      and no table has FORCE ROW LEVEL SECURITY silently zeroing its count.
 *   2. Row count per DIRECT table (the 27 real Postgres tables in supa.js).
 *      A declared table missing from BOTH databases is a FAIL, not a match:
 *      db.js initDb() hydrates every CORE_TABLE and exits the process if one
 *      cannot be read, so Render would crash-loop.
 *   3. Row count per other public table (kv_collections, app_settings and the
 *      legacy tables that a dump carries but the app reads from kv).
 *   4. Row count per kv_collections collection (the 77 operational tables
 *      declared in supa.js today).
 *   5. last_value of every public sequence. lead_status_history.id is
 *      GENERATED BY DEFAULT AS IDENTITY; if the restore leaves its sequence
 *      behind the data, the record_lead_status_change() trigger makes EVERY
 *      parent/student update fail on a duplicate key. A data-only restore is
 *      the classic way to produce exactly that.
 *   6. auth.users / auth.identities / users holding a password hash.
 *      These live in the `auth` schema — a public-schema-only dump loses them
 *      and every staff login fails.
 *   7. Object count and total bytes per storage bucket, plus the public flag.
 *      Bucket objects are NOT carried by a Postgres dump, and 'product-images'
 *      must stay public or every catalog photo 404s.
 *   8. Rows containing the OLD project ref (absolute storage URLs that never
 *      self-heal) — must be 0 on the target after step 04 — AND rows containing
 *      the NEW ref, which must have picked up what the old ref lost. Checking
 *      only "old ref is gone" passes a step-04 bug that blanked the URLs.
 *   9. Presence of every SECURITY DEFINER function, plus the append-only
 *      trigger on kv_collections that seals the signature-evidence journal.
 *      Lost in the restore is a FAIL; absent on both sides means the migration
 *      was never applied to production, which is a WARN.
 *  10. RLS per public table, and whether anon / PUBLIC / authenticated hold
 *      write grants, SELECT grants, or EXECUTE on a SECURITY DEFINER function.
 *
 * Category 10 is judged as a REGRESSION against the source, not as an absolute.
 * A hole that already exists in production today is a WARN (fix it separately —
 * blocking a region move on it only teaches the operator to ignore this gate);
 * a hole the restore OPENED is a FAIL. That distinction is the whole point
 * here: a fresh Supabase project ships ALTER DEFAULT PRIVILEGES granting
 * anon/authenticated on the public schema, so a restore very often re-grants
 * exactly what database/20260814_enforce_api_only_access.sql revoked.
 * Grants are read from pg_class.relacl / pg_proc.proacl with acldefault()
 * applied, so a NULL ACL is correctly reported as "PUBLIC has EXECUTE".
 *
 * ─── WHAT IT DOES *NOT* CHECK ───────────────────────────────────────────────
 * Nothing outside the two databases. In particular it cannot see whether
 * EVIDENCE_SIGNING_SECRET was set on Render to the OLD service_role key, and it
 * cannot see whether the Vercel client was rebuilt against the new anon key.
 * Both are mandatory and both are invisible from here; the run prints them as a
 * reminder on every outcome, PASS or FAIL.
 *
 * ─── USAGE ──────────────────────────────────────────────────────────────────
 *   node migration/05-verify.mjs --target-url "postgresql://postgres.NEWREF:...@aws-1-eu-central-1.pooler.supabase.com:5432/postgres"
 *   node migration/05-verify.mjs                  # target from env / .env.target
 *   node migration/05-verify.mjs --source-only    # pre-migration baseline
 *   node migration/05-verify.mjs --diff-only      # print only rows that differ
 *   node migration/05-verify.mjs --json out.json  # machine-readable report
 *   node migration/05-verify.mjs --help
 *
 * Connection strings resolve in this order (first hit wins):
 *   SOURCE: --source-url, $SOURCE_DATABASE_URL, env-file SOURCE_DATABASE_URL,
 *           $DATABASE_URL, env-file DATABASE_URL
 *   TARGET: --target-url, $TARGET_DATABASE_URL, target-env-file
 *           TARGET_DATABASE_URL or DATABASE_URL, env-file TARGET_DATABASE_URL
 * Use the SESSION-mode pooler (aws-1-<region>.pooler.supabase.com:5432, user
 * postgres.<ref>). The direct db.<ref>.supabase.co host is IPv6-only, and the
 * TRANSACTION-mode pooler on :6543 does not keep `SET` across statements, so
 * the read-only session guard cannot be established there.
 *
 * ─── EXIT CODES ─────────────────────────────────────────────────────────────
 *   0  every category PASSed (WARN does not gate). Cutover may proceed.
 *   1  at least one category FAILed. Do not cut over.
 *   2  the verification could not be run at all (bad config, no connection).
 *
 * Requires Node 20+. Uses only `pg`, already a server/package.json dependency.
 */

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

// ─── Constants ──────────────────────────────────────────────────────────────

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..');

/** The project being migrated away from. Override with --old-ref. */
const DEFAULT_OLD_PROJECT_REF = 'xaxykjvqqhrodmseqleu';

/**
 * Documented sizes of the two table families in server/supa.js.
 * The migration brief was written against 27 + 76 = 103 collections; the repo
 * now declares 27 + 77 = 104 (one operational collection was added since).
 * These numbers are only a drift alarm — the list parsed out of supa.js at
 * runtime is always the authority for what gets verified.
 */
const EXPECTED_DIRECT_TABLES = 27;
const EXPECTED_OPERATIONAL_TABLES = 77;

/** Buckets the app uploads to (server/supa.js), and whether they must be public. */
const REQUIRED_BUCKETS = [
  { name: 'product-images', mustBePublic: true },
  { name: 'client-documents', mustBePublic: false },
  { name: 'employee-documents', mustBePublic: false },
];

/**
 * SECURITY DEFINER functions the CRM depends on, by identity signature.
 * Sources: database/20260726_sales_workflow.sql,
 *          database/20260805_participation_forms_rebuild.sql,
 *          database/20260805_signature_evidence.sql,
 *          database/20260813_registration_lifecycle.sql
 */
const REQUIRED_SECDEF_FUNCTIONS = [
  'claim_group_placement_hold(p_hold jsonb)',
  'claim_registration_lifecycle_event(p_event jsonb)',
  'prevent_signature_evidence_mutation()',
  'punch_customer_pass(p_pass_id text, p_punch_id text, p_punch_data jsonb)',
  'record_lead_status_change()',
];

/** Trigger that makes the signature-evidence journal append-only. */
const APPEND_ONLY_TRIGGER = {
  table: 'kv_collections',
  name: 'signature_evidence_is_append_only',
};

/** Tables exempt from the "RLS must be on" rule (PostGIS bookkeeping). */
const RLS_EXEMPT_TABLES = new Set(['spatial_ref_sys']);

/** Roles that must not be able to write anything in the public schema. */
const PUBLIC_ROLES = ['anon', 'PUBLIC', 'authenticated'];
const WRITE_PRIVILEGES = new Set([
  'INSERT',
  'UPDATE',
  'DELETE',
  'TRUNCATE',
  'REFERENCES',
  'TRIGGER',
]);

const VALID_IDENTIFIER = /^[a-z_][a-z0-9_]*$/;

/** Supabase project refs are 20 lowercase letters; accept a little slack. */
const PROJECT_REF_PATTERN = /^[a-z0-9]{12,40}$/;

/** Session-mode pooler port. :6543 is transaction mode and cannot hold `SET`. */
const SESSION_POOLER_PORT = '5432';

// ─── Tiny output helpers ────────────────────────────────────────────────────

const useColor = Boolean(process.stdout.isTTY) && !process.env.NO_COLOR;
const paint = (code, text) => (useColor ? `[${code}m${text}[0m` : text);
const green = (t) => paint('32', t);
const red = (t) => paint('31;1', t);
const yellow = (t) => paint('33', t);
const dim = (t) => paint('2', t);
const bold = (t) => paint('1', t);

export const STATUS = { PASS: 'PASS', FAIL: 'FAIL', WARN: 'WARN', INFO: 'INFO' };

function paintStatus(status) {
  if (status === STATUS.PASS) return green('PASS');
  if (status === STATUS.FAIL) return red('FAIL');
  if (status === STATUS.WARN) return yellow('WARN');
  return dim('INFO');
}

const numberFormat = new Intl.NumberFormat('en-US');
const fmtNum = (value) =>
  value === null || value === undefined ? '—' : numberFormat.format(value);

function fmtBytes(value) {
  if (value === null || value === undefined) return '—';
  const units = ['B', 'KB', 'MB', 'GB', 'TB'];
  let n = Number(value);
  let unit = 0;
  while (n >= 1024 && unit < units.length - 1) {
    n /= 1024;
    unit += 1;
  }
  const shown = unit === 0 ? String(Math.round(n)) : n.toFixed(1);
  return `${shown} ${units[unit]}`;
}

/** Column-aligned ASCII table. `align` is a string of 'l'/'r' per column. */
function renderTable(headers, rows, align) {
  if (!rows.length) return;
  const columns = headers.length;
  const visibleLength = (text) => String(text).replace(/\[[0-9;]*m/g, '').length;
  const widths = headers.map((header, index) =>
    Math.max(
      visibleLength(header),
      ...rows.map((row) => visibleLength(row[index] ?? ''))
    )
  );
  const padCell = (text, index) => {
    const raw = String(text ?? '');
    const gap = widths[index] - visibleLength(raw);
    const pad = ' '.repeat(Math.max(0, gap));
    return align[index] === 'r' ? pad + raw : raw + pad;
  };
  const line = (cells) =>
    cells.map((cell, index) => padCell(cell, index)).join('  ').trimEnd();

  console.log(dim(line(headers)));
  console.log(dim(widths.map((width) => '-'.repeat(width)).join('  ')));
  for (const row of rows) console.log(line(row.slice(0, columns)));
}

// ─── CLI ────────────────────────────────────────────────────────────────────

const HELP = `
migration/05-verify.mjs — read-only SOURCE vs TARGET verification gate.

  --source-url <conn>        Source (old project) connection string.
  --target-url <conn>        Target (new project) connection string.
  --env-file <path>          Defaults to <repo>/server/.env
  --target-env <path>        Defaults to <repo>/migration/.env.target
  --old-ref <ref>            Old project ref to scan for. Falls back to $OLD_REF,
                             then ${DEFAULT_OLD_PROJECT_REF}
  --new-ref <ref>            New project ref the rewritten URLs must now carry.
                             Derived from the target connection user when omitted.
  --source-only              Snapshot the source alone (baseline, NOT a gate).
  --diff-only                Print only rows that are not PASS.
  --json <path>              Write a machine-readable report (no secrets).
  --statement-timeout <ms>   Per-statement timeout. Default 300000.
  --strict-ssl               Verify the server TLS certificate chain.
  --no-ssl                   Connect without TLS (local Postgres only).
  --help

Exit codes: 0 all PASS, 1 a category FAILed, 2 could not run.
`;

function parseArgs(argv) {
  const options = {
    sourceUrl: '',
    targetUrl: '',
    envFile: '',
    targetEnvFile: '',
    oldRef: DEFAULT_OLD_PROJECT_REF,
    oldRefExplicit: false,
    newRef: '',
    sourceOnly: false,
    diffOnly: false,
    jsonPath: '',
    statementTimeout: 300000,
    strictSsl: false,
    noSsl: false,
    help: false,
  };
  const takeValue = (index, flag) => {
    const value = argv[index + 1];
    if (value === undefined || value.startsWith('--')) {
      throw new Error(`${flag} needs a value`);
    }
    return value;
  };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    switch (arg) {
      case '--source-url': options.sourceUrl = takeValue(index, arg); index += 1; break;
      case '--target-url': options.targetUrl = takeValue(index, arg); index += 1; break;
      case '--env-file': options.envFile = takeValue(index, arg); index += 1; break;
      case '--target-env': options.targetEnvFile = takeValue(index, arg); index += 1; break;
      case '--old-ref':
        options.oldRef = takeValue(index, arg);
        options.oldRefExplicit = true;
        index += 1;
        break;
      case '--new-ref': options.newRef = takeValue(index, arg); index += 1; break;
      case '--json': options.jsonPath = takeValue(index, arg); index += 1; break;
      case '--statement-timeout':
        options.statementTimeout = Number(takeValue(index, arg));
        index += 1;
        break;
      case '--source-only': options.sourceOnly = true; break;
      case '--diff-only': options.diffOnly = true; break;
      case '--strict-ssl': options.strictSsl = true; break;
      case '--no-ssl': options.noSsl = true; break;
      case '--help':
      case '-h': options.help = true; break;
      default:
        throw new Error(`Unknown argument: ${arg}`);
    }
  }
  if (!Number.isFinite(options.statementTimeout) || options.statementTimeout < 1000) {
    throw new Error('--statement-timeout must be at least 1000 (ms)');
  }
  // An empty or short ref would turn strpos(row::text, ref) into "matches
  // everything" and silently report the whole database as contaminated.
  for (const [flag, value] of [['--old-ref', options.oldRef], ['--new-ref', options.newRef]]) {
    if (value && !PROJECT_REF_PATTERN.test(value)) {
      throw new Error(`${flag} does not look like a Supabase project ref: "${value}"`);
    }
  }
  if (!options.oldRef) throw new Error('--old-ref must not be empty');
  return options;
}

// ─── Config loading (no dotenv dependency, never printed) ───────────────────

/** Parse a .env file into a plain object. Values are never logged. */
function readEnvFile(filePath) {
  const text = fs.readFileSync(filePath, 'utf8');
  const values = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const withoutExport = line.startsWith('export ') ? line.slice(7).trim() : line;
    const equals = withoutExport.indexOf('=');
    if (equals <= 0) continue;
    const key = withoutExport.slice(0, equals).trim();
    let value = withoutExport.slice(equals + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"') && value.length > 1) ||
      (value.startsWith("'") && value.endsWith("'") && value.length > 1)
    ) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

/**
 * `server/.env` is git-ignored, so a linked worktree does not have one.
 * Follow the .git pointer file back to the main checkout and use its copy.
 */
function mainCheckoutRoot() {
  const gitPath = path.join(REPO_ROOT, '.git');
  try {
    if (!fs.statSync(gitPath).isFile()) return '';
    const pointer = fs.readFileSync(gitPath, 'utf8').trim();
    const match = pointer.match(/^gitdir:\s*(.+)$/m);
    if (!match) return '';
    const gitDir = match[1].trim().replace(/\\/g, '/');
    const at = gitDir.indexOf('/.git/worktrees/');
    if (at === -1) return '';
    return gitDir.slice(0, at);
  } catch {
    return '';
  }
}

function resolveEnvFile(explicitPath) {
  if (explicitPath) {
    if (!fs.existsSync(explicitPath)) throw new Error(`env file not found: ${explicitPath}`);
    return explicitPath;
  }
  const candidates = [path.join(REPO_ROOT, 'server', '.env')];
  const mainRoot = mainCheckoutRoot();
  if (mainRoot) candidates.push(path.join(mainRoot, 'server', '.env'));
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate;
  }
  return '';
}

/** Strip the password so a connection can be described in the output. */
function describeConnection(connectionString) {
  try {
    const url = new URL(connectionString);
    const user = decodeURIComponent(url.username || '');
    const database = url.pathname.replace(/^\//, '') || 'postgres';
    const port = url.port || '5432';
    return `${user}@${url.hostname}:${port}/${database}`;
  } catch {
    return '<unparseable connection string>';
  }
}

/** Supabase pooler users are `postgres.<project-ref>`. */
function projectRefOf(connectionString) {
  try {
    const url = new URL(connectionString);
    const user = decodeURIComponent(url.username || '');
    const dot = user.indexOf('.');
    if (dot === -1) return '';
    const ref = user.slice(dot + 1).trim().toLowerCase();
    return PROJECT_REF_PATTERN.test(ref) ? ref : '';
  } catch {
    return '';
  }
}

function hostOf(connectionString) {
  try {
    return new URL(connectionString).hostname;
  } catch {
    return '';
  }
}

/** `https://<ref>.supabase.co` -> `<ref>`. Same rule 04-rewrite-urls.mjs uses. */
function refFromSupabaseUrl(value) {
  const match = String(value || '').match(/https?:\/\/([a-z0-9]{12,40})\.supabase\.(co|in)/i);
  return match ? match[1].toLowerCase() : '';
}

// ─── The table inventory, read from server/supa.js ──────────────────────────

/**
 * Read DIRECT_TABLES / OPERATIONAL_TABLES out of server/supa.js instead of
 * duplicating them here: a table added to the app but not to this list would
 * otherwise be verified by nobody.
 */
function parseTableList(source, constantName) {
  const start = source.indexOf(`${constantName} = [`);
  if (start === -1) throw new Error(`${constantName} not found in server/supa.js`);
  const open = source.indexOf('[', start);
  const close = source.indexOf('\n];', open);
  if (close === -1) throw new Error(`${constantName} array is not terminated in server/supa.js`);
  const body = source.slice(open + 1, close).replace(/\/\/[^\n]*/g, '');
  const names = [...body.matchAll(/'([A-Za-z0-9_]+)'/g)].map((match) => match[1]);
  const unique = [...new Set(names)];
  if (!unique.length) throw new Error(`${constantName} parsed as empty from server/supa.js`);
  for (const name of unique) {
    if (!VALID_IDENTIFIER.test(name)) {
      throw new Error(`${constantName} contains an unusable identifier: ${name}`);
    }
  }
  return unique;
}

function loadTableInventory() {
  const supaPath = path.join(REPO_ROOT, 'server', 'supa.js');
  const source = fs.readFileSync(supaPath, 'utf8');
  return {
    supaPath,
    direct: parseTableList(source, 'DIRECT_TABLES'),
    operational: parseTableList(source, 'OPERATIONAL_TABLES'),
  };
}

// ─── Read-only SQL plumbing ─────────────────────────────────────────────────

function loadPgModule() {
  const candidates = [
    path.join(REPO_ROOT, 'server', 'package.json'),
    path.join(REPO_ROOT, 'package.json'),
  ];
  const mainRoot = mainCheckoutRoot();
  if (mainRoot) {
    candidates.push(path.join(mainRoot, 'server', 'package.json'));
    candidates.push(path.join(mainRoot, 'package.json'));
  }
  const problems = [];
  for (const candidate of candidates) {
    try {
      return createRequire(candidate)('pg');
    } catch (error) {
      problems.push(`${candidate}: ${error.message}`);
    }
  }
  throw new Error(
    `could not load the 'pg' module (a server/package.json dependency).\n  ` +
      problems.join('\n  ') +
      `\n  Fix: run "npm install" inside server/.`
  );
}

function assertReadOnlySql(sql) {
  const withoutComments = sql
    .replace(/\/\*[\s\S]*?\*\//g, ' ')
    .replace(/--[^\n]*/g, ' ')
    .trim();
  if (!/^(select|with|show)\b/i.test(withoutComments)) {
    throw new Error(
      `BLOCKED: 05-verify is read-only and refuses to send: ${withoutComments.slice(0, 80)}`
    );
  }
  if (withoutComments.replace(/;\s*$/, '').includes(';')) {
    throw new Error('BLOCKED: 05-verify refuses batched statements');
  }
}

function sslConfig(connectionString, options) {
  if (options.noSsl) return false;
  let sslmode = '';
  try {
    sslmode = new URL(connectionString).searchParams.get('sslmode') || '';
  } catch {
    sslmode = '';
  }
  if (sslmode === 'disable') return false;
  // Encrypted either way; chain verification is opt-in because the Supabase
  // pooler presents a certificate whose chain many local trust stores reject.
  return { rejectUnauthorized: options.strictSsl };
}

class ReadOnlyConnection {
  constructor(label, connectionString, options, pg) {
    this.label = label;
    this.connectionString = connectionString;
    this.options = options;
    this.pg = pg;
    this.client = null;
    this.queryCount = 0;
  }

  async connect() {
    this.client = new this.pg.Client({
      connectionString: this.connectionString,
      ssl: sslConfig(this.connectionString, this.options),
      application_name: 'crm-migration-05-verify (read-only)',
      connectionTimeoutMillis: 30000,
    });
    await this.client.connect();

    // The only three non-SELECT statements in this file. They are literals;
    // the sole interpolation is a number that has already been range-checked
    // by parseArgs and is rounded again here. They deliberately bypass
    // assertReadOnlySql — everything routed through query() does not.
    const timeoutMs = Math.round(Number(this.options.statementTimeout));
    if (!Number.isFinite(timeoutMs) || timeoutMs < 1000) {
      throw new Error(`${this.label}: refusing to set a bogus statement_timeout`);
    }
    await this.client.query('SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY');
    await this.client.query(`SET statement_timeout = ${timeoutMs}`);
    await this.client.query('SET idle_in_transaction_session_timeout = 60000');

    const check = await this.client.query('SHOW transaction_read_only');
    const value = check.rows[0]?.transaction_read_only;
    if (value !== 'on') {
      throw new Error(
        `${this.label}: could not put the session into read-only mode (got "${value}"). ` +
          'A transaction-mode pooler (:6543) does this — use the SESSION pooler on :5432. Refusing to continue.'
      );
    }
  }

  async query(sql, params = []) {
    assertReadOnlySql(sql);
    this.queryCount += 1;
    return this.client.query(sql, params);
  }

  async end() {
    if (this.client) {
      try {
        await this.client.end();
      } catch {
        /* closing a verification session is not worth failing over */
      }
    }
  }
}

// ─── Collectors (every one of these is a SELECT) ────────────────────────────

const quoteIdent = (name) => {
  if (!VALID_IDENTIFIER.test(name)) throw new Error(`unsafe identifier: ${name}`);
  return `"${name}"`;
};

async function listPublicTables(conn) {
  const result = await conn.query(`
    select c.relname as name,
           c.relrowsecurity as rls_enabled,
           c.relforcerowsecurity as rls_forced
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public'
       and c.relkind in ('r', 'p')
       and not c.relispartition
     order by 1`);
  return result.rows.map((row) => ({
    name: row.name,
    rlsEnabled: row.rls_enabled === true,
    rlsForced: row.rls_forced === true,
  }));
}

async function countRows(conn, tables) {
  const counts = new Map();
  const chunkSize = 12;
  for (let index = 0; index < tables.length; index += chunkSize) {
    const chunk = tables.slice(index, index + chunkSize);
    const sql = chunk
      .map(
        (table) =>
          `select '${table}'::text as table_name, count(*)::bigint as n from public.${quoteIdent(table)}`
      )
      .join('\nunion all\n');
    const result = await conn.query(sql);
    for (const row of result.rows) counts.set(row.table_name, Number(row.n));
  }
  return counts;
}

async function countKvCollections(conn, hasKv) {
  if (!hasKv) return new Map();
  const result = await conn.query(`
    select collection, count(*)::bigint as n
      from public.kv_collections
     group by 1
     order by 1`);
  const counts = new Map();
  for (const row of result.rows) counts.set(row.collection, Number(row.n));
  return counts;
}

async function countAuth(conn) {
  const result = await conn.query(`
    select (select count(*)::bigint from auth.users) as users,
           (select count(*)::bigint from auth.identities) as identities,
           (select count(*)::bigint from auth.users
             where encrypted_password is not null and encrypted_password <> '') as with_password`);
  const row = result.rows[0];
  return {
    users: Number(row.users),
    identities: Number(row.identities),
    withPassword: Number(row.with_password),
  };
}

async function collectBuckets(conn) {
  const result = await conn.query(`
    select b.name,
           b.public as is_public,
           count(o.id)::bigint as objects,
           coalesce(sum((o.metadata->>'size')::bigint), 0)::bigint as bytes,
           count(o.id) filter (where o.metadata->>'size' is null)::bigint as objects_without_size
      from storage.buckets b
      left join storage.objects o on o.bucket_id = b.id
     group by b.name, b.public
     order by 1`);
  const buckets = new Map();
  for (const row of result.rows) {
    buckets.set(row.name, {
      isPublic: row.is_public === true,
      objects: Number(row.objects),
      bytes: Number(row.bytes),
      // An object whose metadata carries no size contributes 0 to `bytes`, so a
      // byte total that matches while these differ is not evidence of anything.
      objectsWithoutSize: Number(row.objects_without_size),
    });
  }
  return buckets;
}

/**
 * Rows anywhere in the public schema that mention the OLD project ref, and — in
 * the same pass — rows that mention the NEW one. The whole row is cast to text,
 * so a ref hiding in any column or inside a jsonb blob is caught.
 * kv_collections is reported per collection because that is where the 42
 * pricelist.image URLs live (as data->>'image', not as a column).
 *
 * Counting BOTH refs in one scan is what makes this a real check. "Old ref is
 * gone" alone is satisfied just as well by step 04 having blanked the URLs; the
 * new-ref count is what proves the rewrite produced working URLs. The two
 * counters ride on a single sequential scan, so this costs no more than before.
 *
 * newRef may be '' (source-only runs, or an unparseable target URL). It is then
 * left out of the SQL entirely — strpos(anything, '') returns 1, which would
 * report every row in the database as a hit.
 */
async function scanRefs(conn, tables, oldRef, newRef) {
  if (!oldRef) throw new Error('scanRefs called without an old ref');
  const wantNew = Boolean(newRef) && newRef !== oldRef;
  const newExpr = wantNew
    ? `, count(*) filter (where strpos(row_scan::text, $2) > 0)::bigint as new_n`
    : `, 0::bigint as new_n`;
  const params = wantNew ? [oldRef, newRef] : [oldRef];

  const perTable = new Map();
  const perTableNew = new Map();
  const perCollection = new Map();
  const perCollectionNew = new Map();
  let total = 0;
  let totalNew = 0;

  for (const table of tables) {
    if (table === 'kv_collections') {
      const result = await conn.query(
        `select collection,
                count(*) filter (where strpos(row_scan::text, $1) > 0)::bigint as n
                ${newExpr}
           from public.kv_collections row_scan
          group by 1
         having count(*) filter (where strpos(row_scan::text, $1) > 0) > 0
             or ${wantNew ? 'count(*) filter (where strpos(row_scan::text, $2) > 0) > 0' : 'false'}
          order by 1`,
        params
      );
      let tableTotal = 0;
      let tableTotalNew = 0;
      for (const row of result.rows) {
        const hits = Number(row.n);
        const hitsNew = Number(row.new_n);
        if (hits) perCollection.set(row.collection, hits);
        if (hitsNew) perCollectionNew.set(row.collection, hitsNew);
        tableTotal += hits;
        tableTotalNew += hitsNew;
      }
      if (tableTotal) perTable.set('kv_collections', tableTotal);
      if (tableTotalNew) perTableNew.set('kv_collections', tableTotalNew);
      total += tableTotal;
      totalNew += tableTotalNew;
      continue;
    }
    const result = await conn.query(
      `select count(*) filter (where strpos(row_scan::text, $1) > 0)::bigint as n
              ${newExpr}
         from public.${quoteIdent(table)} row_scan`,
      params
    );
    const hits = Number(result.rows[0].n);
    const hitsNew = Number(result.rows[0].new_n);
    if (hits) perTable.set(table, hits);
    if (hitsNew) perTableNew.set(table, hitsNew);
    total += hits;
    totalNew += hitsNew;
  }
  return {
    total,
    perTable,
    perCollection,
    newScanned: wantNew,
    totalNew: wantNew ? totalNew : null,
    perTableNew,
    perCollectionNew,
  };
}

/**
 * last_value of every sequence in the public schema.
 *
 * This is the failure a row-count check cannot see. public.lead_status_history
 * has `id bigint GENERATED BY DEFAULT AS IDENTITY`
 * (database/20260726_sales_workflow.sql:7), and the SECURITY DEFINER trigger
 * record_lead_status_change() inserts into it on every parents/students status
 * change. Restore the rows without advancing the sequence and the first status
 * change after cutover dies on a duplicate primary key — every parent and
 * student update in the CRM fails, with a perfectly matching row count.
 *
 * Reading pg_sequences.last_value does NOT consume a value; it is a plain read.
 */
async function collectSequences(conn) {
  const result = await conn.query(`
    select sequencename as name, last_value
      from pg_sequences
     where schemaname = 'public'
     order by 1`);
  const sequences = new Map();
  for (const row of result.rows) {
    sequences.set(row.name, row.last_value === null ? null : Number(row.last_value));
  }
  return sequences;
}

async function collectFunctions(conn) {
  const result = await conn.query(`
    select p.proname as name,
           pg_get_function_identity_arguments(p.oid) as args,
           p.prosecdef as security_definer
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public'
       and p.prokind in ('f', 'p')
     order by 1, 2`);
  const functions = new Map();
  for (const row of result.rows) {
    functions.set(`${row.name}(${row.args})`, {
      securityDefiner: row.security_definer === true,
    });
  }
  return functions;
}

async function collectTrigger(conn, hasTable) {
  if (!hasTable) return false;
  const result = await conn.query(
    `select count(*)::bigint as n
       from pg_trigger t
       join pg_class c on c.oid = t.tgrelid
       join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public'
        and c.relname = $1
        and t.tgname = $2
        and not t.tgisinternal`,
    [APPEND_ONLY_TRIGGER.table, APPEND_ONLY_TRIGGER.name]
  );
  return Number(result.rows[0].n) > 0;
}

/**
 * Grants read from the catalog, not information_schema: information_schema
 * filters by the querying role, and a NULL acl must be expanded with
 * acldefault() — for functions that default grants EXECUTE to PUBLIC.
 */
async function collectTableGrants(conn) {
  const result = await conn.query(`
    select c.relname as name,
           case when a.grantee = 0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end as grantee,
           a.privilege_type
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      cross join lateral aclexplode(coalesce(c.relacl, acldefault('r', c.relowner))) a
     where n.nspname = 'public'
       and c.relkind in ('r', 'p', 'v', 'm', 'f')
     order by 1, 2, 3`);
  return result.rows.map((row) => ({
    name: row.name,
    grantee: row.grantee,
    privilege: row.privilege_type,
  }));
}

async function collectFunctionGrants(conn) {
  const result = await conn.query(`
    select p.proname as name,
           pg_get_function_identity_arguments(p.oid) as args,
           p.prosecdef as security_definer,
           case when a.grantee = 0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end as grantee,
           a.privilege_type
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
      cross join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a
     where n.nspname = 'public'
     order by 1, 4`);
  return result.rows.map((row) => ({
    signature: `${row.name}(${row.args})`,
    securityDefiner: row.security_definer === true,
    grantee: row.grantee,
    privilege: row.privilege_type,
  }));
}

async function serverVersion(conn) {
  const result = await conn.query('select version() as v');
  return String(result.rows[0].v).split(' ').slice(0, 2).join(' ');
}

/** Everything this script reads from one side. Each part fails independently. */
async function snapshot(conn, inventory, oldRef, newRef) {
  const data = { label: conn.label, errors: {} };

  const guard = async (key, fn, fallback) => {
    try {
      data[key] = await fn();
    } catch (error) {
      data.errors[key] = error.message;
      data[key] = fallback;
    }
  };

  await guard('version', () => serverVersion(conn), 'unknown');
  await guard('publicTables', () => listPublicTables(conn), []);

  const present = new Set(data.publicTables.map((table) => table.name));
  const directPresent = inventory.direct.filter((table) => present.has(table));
  const otherPresent = data.publicTables
    .map((table) => table.name)
    .filter((name) => !inventory.direct.includes(name));

  data.presentTables = present;
  await guard('directCounts', () => countRows(conn, directPresent), new Map());
  await guard('otherCounts', () => countRows(conn, otherPresent), new Map());
  await guard('kvCounts', () => countKvCollections(conn, present.has('kv_collections')), new Map());
  await guard('sequences', () => collectSequences(conn), null);
  await guard('auth', () => countAuth(conn), null);
  await guard('buckets', () => collectBuckets(conn), new Map());
  await guard(
    'refScan',
    () => scanRefs(conn, [...present].sort(), oldRef, newRef),
    {
      total: null,
      perTable: new Map(),
      perCollection: new Map(),
      newScanned: false,
      totalNew: null,
      perTableNew: new Map(),
      perCollectionNew: new Map(),
    }
  );
  await guard('functions', () => collectFunctions(conn), new Map());
  await guard('appendOnlyTrigger', () => collectTrigger(conn, present.has('kv_collections')), null);
  await guard('tableGrants', () => collectTableGrants(conn), []);
  await guard('functionGrants', () => collectFunctionGrants(conn), []);

  return data;
}

// ─── Comparison ─────────────────────────────────────────────────────────────

class Report {
  constructor(options) {
    this.options = options;
    this.categories = [];
  }

  category(title, note = '') {
    const entry = { title, note, rows: [], failures: 0, warnings: 0, passes: 0, infos: 0 };
    this.categories.push(entry);
    return entry;
  }

  static addRow(category, check, source, target, status, note = '') {
    category.rows.push({ check, source, target, status, note });
    if (status === STATUS.FAIL) category.failures += 1;
    else if (status === STATUS.WARN) category.warnings += 1;
    else if (status === STATUS.INFO) category.infos += 1;
    else category.passes += 1;
  }

  print() {
    for (const category of this.categories) {
      const shown = this.options.diffOnly
        ? category.rows.filter((row) => row.status !== STATUS.PASS)
        : category.rows;
      console.log('');
      console.log(bold(category.title) + (category.note ? dim(`  (${category.note})`) : ''));
      if (!shown.length) {
        console.log(dim('  all rows matched'));
      } else {
        renderTable(
          ['CHECK', 'SOURCE', 'TARGET', 'STATUS', 'NOTE'],
          shown.map((row) => [
            `  ${row.check}`,
            row.source,
            row.target,
            paintStatus(row.status),
            row.note ? dim(row.note) : '',
          ]),
          ['l', 'r', 'r', 'l', 'l']
        );
      }
      const status = categoryStatus(category);
      const summary =
        status === STATUS.PASS
          ? `${category.rows.length} checks, all matched`
          : status === STATUS.INFO
            ? `${category.rows.length} values recorded (baseline, nothing compared)`
            : `${category.failures} failed, ${category.warnings} warnings, ${category.rows.length} checks`;
      console.log(`  ${paintStatus(status)}  ${category.title} — ${summary}`);
    }
  }

  get failed() {
    return this.categories.some((category) => categoryStatus(category) === STATUS.FAIL);
  }
}

/** A category is only INFO when nothing in it was actually compared. */
export function categoryStatus(category) {
  if (category.failures > 0) return STATUS.FAIL;
  if (category.warnings > 0) return STATUS.WARN;
  if (category.passes === 0 && category.infos > 0) return STATUS.INFO;
  return STATUS.PASS;
}

const addRow = Report.addRow;

/**
 * Shared count comparison used for tables and kv collections.
 *
 * `missingBothNote`, when given, turns "absent on BOTH sides" from a silent
 * match into a FAIL. That case is not a match at all: for a table declared in
 * supa.js it means db.js initDb() will fail to hydrate it and the Render
 * process will exit, whichever database you point at.
 */
function compareCountMaps(
  category,
  keys,
  sourceCounts,
  targetCounts,
  sourceOnly,
  describe,
  missingBothNote
) {
  for (const key of keys) {
    const sourceValue = sourceCounts.has(key) ? sourceCounts.get(key) : null;
    const targetValue = targetCounts.has(key) ? targetCounts.get(key) : null;
    const note = describe ? describe(key, sourceValue, targetValue) : '';

    if (sourceValue === null && targetValue === null && missingBothNote) {
      addRow(
        category,
        key,
        red('absent'),
        sourceOnly ? dim('n/a') : red('absent'),
        STATUS.FAIL,
        missingBothNote
      );
      continue;
    }
    if (sourceOnly) {
      addRow(
        category,
        key,
        sourceValue === null ? red('absent') : fmtNum(sourceValue),
        dim('n/a'),
        sourceValue === null && missingBothNote ? STATUS.FAIL : STATUS.INFO,
        note
      );
      continue;
    }
    if (sourceValue === null && targetValue !== null) {
      addRow(category, key, dim('absent'), fmtNum(targetValue), STATUS.WARN, note || 'only on target');
      continue;
    }
    if (sourceValue !== null && targetValue === null) {
      addRow(category, key, fmtNum(sourceValue), red('MISSING'), STATUS.FAIL, note || 'missing on target');
      continue;
    }
    if (sourceValue === targetValue) {
      addRow(category, key, fmtNum(sourceValue), fmtNum(targetValue), STATUS.PASS, note);
      continue;
    }
    const delta = targetValue - sourceValue;
    addRow(
      category,
      key,
      fmtNum(sourceValue),
      fmtNum(targetValue),
      STATUS.FAIL,
      `${delta > 0 ? '+' : ''}${fmtNum(delta)} vs source`
    );
  }
}

export function buildReport(options, inventory, source, target) {
  const report = new Report(options);
  const sourceOnly = options.sourceOnly;
  const emptyMap = new Map();
  const tgt = target || { errors: {}, presentTables: new Set() };

  // ── 0. inventory sanity ───────────────────────────────────────────────────
  const inventoryCategory = report.category(
    '0. Table inventory (server/supa.js)',
    'the lists this run verified against'
  );
  addRow(
    inventoryCategory,
    'DIRECT_TABLES parsed',
    fmtNum(inventory.direct.length),
    fmtNum(EXPECTED_DIRECT_TABLES),
    inventory.direct.length === EXPECTED_DIRECT_TABLES ? STATUS.PASS : STATUS.WARN,
    inventory.direct.length === EXPECTED_DIRECT_TABLES ? '' : 'supa.js changed since this kit was written'
  );
  addRow(
    inventoryCategory,
    'OPERATIONAL_TABLES parsed',
    fmtNum(inventory.operational.length),
    fmtNum(EXPECTED_OPERATIONAL_TABLES),
    inventory.operational.length === EXPECTED_OPERATIONAL_TABLES ? STATUS.PASS : STATUS.WARN,
    inventory.operational.length === EXPECTED_OPERATIONAL_TABLES
      ? ''
      : 'supa.js changed since this kit was written'
  );

  // ── 1. sanity of the comparison itself ────────────────────────────────────
  const errorCategory = report.category(
    '1. Sanity of this comparison',
    'a query that could not run, or a baseline that is empty, invalidates everything below'
  );
  const errorKeys = new Set([
    ...Object.keys(source.errors || {}),
    ...Object.keys(tgt.errors || {}),
  ]);
  for (const key of [...errorKeys].sort()) {
    addRow(
      errorCategory,
      `collector ${key}`,
      source.errors?.[key] ? red('error') : green('ok'),
      sourceOnly ? dim('n/a') : tgt.errors?.[key] ? red('error') : green('ok'),
      STATUS.FAIL,
      (source.errors?.[key] || tgt.errors?.[key] || '').slice(0, 90)
    );
  }
  if (!errorKeys.size) {
    addRow(errorCategory, 'every query ran', green('ok'), sourceOnly ? dim('n/a') : green('ok'), STATUS.PASS);
  }

  /**
   * Two empty databases match on every count in this report. If the source
   * baseline is empty the run proves nothing at all, so say so instead of
   * printing a wall of green.
   */
  const sumMap = (map) => [...(map?.values() || [])].reduce((total, n) => total + (n || 0), 0);
  const sourceRowTotal = sumMap(source.directCounts) + sumMap(source.otherCounts);
  const targetRowTotal = sumMap(tgt.directCounts) + sumMap(tgt.otherCounts);
  addRow(
    errorCategory,
    'rows read on the source (all public tables)',
    fmtNum(sourceRowTotal),
    sourceOnly ? dim('n/a') : fmtNum(targetRowTotal),
    sourceRowTotal > 0 ? STATUS.PASS : STATUS.FAIL,
    sourceRowTotal > 0
      ? 'a non-empty baseline — the counts below mean something'
      : 'the SOURCE read as EMPTY. Wrong connection string, or you pointed at the new project. Every match below is vacuous.'
  );

  const majorOf = (version) => String(version || '').match(/\b(\d+)\./)?.[1] || '';
  const sourceMajor = majorOf(source.version);
  const targetMajor = majorOf(tgt.version);
  addRow(
    errorCategory,
    'PostgreSQL engine',
    String(source.version || 'unknown'),
    sourceOnly ? dim('n/a') : String(tgt.version || 'unknown'),
    sourceOnly || !targetMajor || sourceMajor === targetMajor ? STATUS.PASS : STATUS.WARN,
    sourceOnly || !targetMajor || sourceMajor === targetMajor
      ? ''
      : `major version differs (${sourceMajor} -> ${targetMajor}); re-read the restore log before trusting it`
  );

  /**
   * FORCE ROW LEVEL SECURITY applies RLS to the table owner as well. With no
   * matching policy, count(*) then returns 0 for this session on BOTH sides and
   * the row-count comparison silently agrees about nothing.
   */
  const forcedRls = [
    ...new Set([
      ...(source.publicTables || []).filter((table) => table.rlsForced).map((table) => table.name),
      ...(tgt.publicTables || []).filter((table) => table.rlsForced).map((table) => table.name),
    ]),
  ].sort();
  if (forcedRls.length) {
    addRow(
      errorCategory,
      'tables with FORCE ROW LEVEL SECURITY',
      fmtNum((source.publicTables || []).filter((table) => table.rlsForced).length),
      sourceOnly
        ? dim('n/a')
        : fmtNum((tgt.publicTables || []).filter((table) => table.rlsForced).length),
      STATUS.WARN,
      `row counts for ${forcedRls.slice(0, 4).join(', ')} may be policy-filtered, not real`
    );
  }

  // ── 2. direct tables ──────────────────────────────────────────────────────
  const directCategory = report.category(
    `2. DIRECT tables — row counts (${inventory.direct.length} real Postgres tables)`
  );
  compareCountMaps(
    directCategory,
    inventory.direct,
    source.directCounts || emptyMap,
    tgt.directCounts || emptyMap,
    sourceOnly,
    null,
    'declared in supa.js but present in NEITHER database — db.js initDb() exits the process'
  );

  // ── 3. other public tables ────────────────────────────────────────────────
  const otherKeys = [
    ...new Set([
      ...(source.otherCounts?.keys() || []),
      ...(tgt.otherCounts?.keys() || []),
    ]),
  ].sort();
  const otherCategory = report.category(
    `3. Other public tables — row counts (${otherKeys.length})`,
    'kv_collections, app_settings and legacy tables a dump still carries'
  );
  compareCountMaps(
    otherCategory,
    otherKeys,
    source.otherCounts || emptyMap,
    tgt.otherCounts || emptyMap,
    sourceOnly
  );

  // ── 4. kv collections ─────────────────────────────────────────────────────
  const declared = new Set(inventory.operational);
  const kvKeys = [
    ...new Set([
      ...inventory.operational,
      ...(source.kvCounts?.keys() || []),
      ...(tgt.kvCounts?.keys() || []),
    ]),
  ].sort();
  const kvCategory = report.category(
    `4. kv_collections — rows per collection (${inventory.operational.length} declared)`,
    'a declared collection with no rows on either side is normal'
  );
  const kvSource = new Map(source.kvCounts || emptyMap);
  const kvTarget = new Map(tgt.kvCounts || emptyMap);
  for (const key of kvKeys) {
    if (declared.has(key)) {
      if (!kvSource.has(key)) kvSource.set(key, 0);
      if (!sourceOnly && !kvTarget.has(key)) kvTarget.set(key, 0);
    }
  }
  compareCountMaps(kvCategory, kvKeys, kvSource, kvTarget, sourceOnly, (key) =>
    declared.has(key) ? '' : 'not declared in supa.js — the server will not hydrate it'
  );

  // ── 5. sequences ──────────────────────────────────────────────────────────
  const sequenceCategory = report.category(
    '5. Sequence positions',
    'a sequence left behind its data breaks the next INSERT, with matching row counts'
  );
  const sourceSequences = source.sequences;
  const targetSequences = tgt.sequences;
  if (!sourceSequences) {
    addRow(
      sequenceCategory,
      'pg_sequences',
      red('unreadable'),
      sourceOnly ? dim('n/a') : red('unreadable'),
      STATUS.FAIL,
      'could not read pg_sequences on the source'
    );
  } else if (!sourceOnly && !targetSequences) {
    addRow(sequenceCategory, 'pg_sequences', green('ok'), red('unreadable'), STATUS.FAIL, 'could not read pg_sequences on the target');
  } else {
    const sequenceNames = [
      ...new Set([...sourceSequences.keys(), ...(targetSequences?.keys() || [])]),
    ].sort();
    if (!sequenceNames.length) {
      addRow(
        sequenceCategory,
        'no sequences in the public schema',
        dim('0'),
        sourceOnly ? dim('n/a') : dim('0'),
        STATUS.PASS,
        'nothing to advance'
      );
    }
    for (const name of sequenceNames) {
      // Existence and value are different questions: pg_sequences.last_value is
      // NULL for a sequence that has never been advanced, and for one the
      // caller cannot read. Neither means "missing".
      const onSource = sourceSequences.has(name);
      const onTarget = Boolean(targetSequences?.has(name));
      const sourceValue = onSource ? sourceSequences.get(name) : null;
      const targetValue = onTarget ? targetSequences.get(name) : null;
      if (sourceOnly) {
        addRow(
          sequenceCategory,
          name,
          sourceValue === null ? dim('unused/unreadable') : fmtNum(sourceValue),
          dim('n/a'),
          STATUS.INFO
        );
        continue;
      }
      if (onSource && !onTarget) {
        addRow(sequenceCategory, name, fmtNum(sourceValue), red('MISSING'), STATUS.FAIL, 'sequence not restored');
        continue;
      }
      if (!onSource) {
        addRow(sequenceCategory, name, dim('absent'), fmtNum(targetValue), STATUS.WARN, 'only on target');
        continue;
      }
      if (sourceValue === null || targetValue === null) {
        addRow(
          sequenceCategory,
          name,
          sourceValue === null ? dim('unused') : fmtNum(sourceValue),
          targetValue === null ? dim('unused') : fmtNum(targetValue),
          sourceValue === null ? STATUS.PASS : STATUS.FAIL,
          sourceValue === null
            ? 'never advanced on the source — nothing to carry over'
            : 'the source has advanced this sequence and the target reports no value'
        );
        continue;
      }
      // Ahead is safe (Supabase restores sometimes over-advance). Behind is the
      // duplicate-key bomb.
      const ok = targetValue !== null && targetValue >= sourceValue;
      addRow(
        sequenceCategory,
        name,
        fmtNum(sourceValue),
        fmtNum(targetValue),
        ok ? STATUS.PASS : STATUS.FAIL,
        ok
          ? targetValue === sourceValue
            ? ''
            : `${fmtNum(targetValue - sourceValue)} ahead of source (safe)`
          : 'BEHIND the source — the next INSERT will collide on the primary key'
      );
    }
  }

  // ── 6. auth schema ────────────────────────────────────────────────────────
  const authCategory = report.category(
    '6. auth schema',
    'auth.users and auth.identities are outside the public schema'
  );
  const authRows = [
    ['auth.users', 'users'],
    ['auth.identities', 'identities'],
    ['auth.users with a password hash', 'withPassword'],
  ];
  for (const [label, key] of authRows) {
    const sourceValue = source.auth ? source.auth[key] : null;
    const targetValue = tgt.auth ? tgt.auth[key] : null;
    if (sourceOnly) {
      addRow(authCategory, label, fmtNum(sourceValue), dim('n/a'), STATUS.INFO);
      continue;
    }
    const status = sourceValue !== null && sourceValue === targetValue ? STATUS.PASS : STATUS.FAIL;
    addRow(
      authCategory,
      label,
      fmtNum(sourceValue),
      fmtNum(targetValue),
      status,
      status === STATUS.PASS ? '' : 'without both, every staff login fails'
    );
  }

  // ── 7. storage buckets ────────────────────────────────────────────────────
  const bucketNames = [
    ...new Set([
      ...REQUIRED_BUCKETS.map((bucket) => bucket.name),
      ...(source.buckets?.keys() || []),
      ...(tgt.buckets?.keys() || []),
    ]),
  ].sort();
  const bucketCategory = report.category(
    '7. Storage buckets',
    'objects are NOT carried by a Postgres dump'
  );
  for (const name of bucketNames) {
    const required = REQUIRED_BUCKETS.find((bucket) => bucket.name === name);
    const sourceBucket = source.buckets?.get(name) || null;
    const targetBucket = tgt.buckets?.get(name) || null;

    if (sourceOnly) {
      addRow(
        bucketCategory,
        `${name} — objects`,
        fmtNum(sourceBucket?.objects ?? null),
        dim('n/a'),
        sourceBucket ? STATUS.INFO : STATUS.FAIL,
        sourceBucket ? `${fmtBytes(sourceBucket.bytes)}, public=${sourceBucket.isPublic}` : 'bucket missing'
      );
      continue;
    }

    if (!targetBucket) {
      addRow(
        bucketCategory,
        `${name} — bucket`,
        sourceBucket ? green('exists') : dim('absent'),
        red('MISSING'),
        sourceBucket || required ? STATUS.FAIL : STATUS.WARN,
        required?.mustBePublic ? 'create it PUBLIC by hand — no SQL creates it' : 'create it before cutover'
      );
      continue;
    }

    addRow(
      bucketCategory,
      `${name} — objects`,
      fmtNum(sourceBucket?.objects ?? null),
      fmtNum(targetBucket.objects),
      sourceBucket && sourceBucket.objects === targetBucket.objects ? STATUS.PASS : STATUS.FAIL,
      sourceBucket && sourceBucket.objects === targetBucket.objects
        ? ''
        : 'copy the bucket objects, a dump does not move them'
    );
    addRow(
      bucketCategory,
      `${name} — bytes`,
      fmtBytes(sourceBucket?.bytes ?? null),
      fmtBytes(targetBucket.bytes),
      sourceBucket && sourceBucket.bytes === targetBucket.bytes ? STATUS.PASS : STATUS.FAIL,
      sourceBucket && sourceBucket.bytes === targetBucket.bytes
        ? ''
        : `${fmtBytes(Math.abs((targetBucket.bytes || 0) - (sourceBucket?.bytes || 0)))} apart`
    );

    // A byte total that matches while objects carry no size metadata is not
    // evidence the files copied — those objects contribute 0 to both sums.
    const sizelessSource = sourceBucket?.objectsWithoutSize || 0;
    const sizelessTarget = targetBucket.objectsWithoutSize || 0;
    if (sizelessSource || sizelessTarget) {
      addRow(
        bucketCategory,
        `${name} — objects with no size metadata`,
        fmtNum(sizelessSource),
        fmtNum(sizelessTarget),
        STATUS.WARN,
        'these count as 0 bytes on both sides, so the byte total under-reports'
      );
    }

    const expectedPublic = required ? required.mustBePublic : sourceBucket?.isPublic;
    addRow(
      bucketCategory,
      `${name} — public flag`,
      String(sourceBucket?.isPublic ?? '—'),
      String(targetBucket.isPublic),
      targetBucket.isPublic === expectedPublic ? STATUS.PASS : STATUS.FAIL,
      targetBucket.isPublic === expectedPublic
        ? ''
        : expectedPublic
          ? 'must be public or every catalog photo 404s'
          : 'must be private — it holds customer and staff documents'
    );
  }

  // ── 8. project-ref URLs (old must be gone, new must have arrived) ─────────
  const emptyScan = {
    total: null,
    perTable: new Map(),
    perCollection: new Map(),
    newScanned: false,
    totalNew: null,
    perTableNew: new Map(),
    perCollectionNew: new Map(),
  };
  const sourceRef = source.refScan || emptyScan;
  const targetRef = tgt.refScan || emptyScan;
  const refCategory = report.category(
    `8. Absolute storage URLs — old ref "${options.oldRef}" out, new ref "${
      options.newRef || '(unknown)'
    }" in`,
    'server/supa.js storeImageValue returns an existing http URL unchanged, so these never self-heal'
  );
  const refKeys = [
    ...new Set([
      ...sourceRef.perTable.keys(),
      ...targetRef.perTable.keys(),
      ...targetRef.perTableNew.keys(),
    ]),
  ].sort();
  for (const key of refKeys) {
    const sourceHits = sourceRef.perTable.get(key) || 0;
    const targetHits = targetRef.perTable.get(key) || 0;
    addRow(
      refCategory,
      `${key} — old ref`,
      fmtNum(sourceHits),
      sourceOnly ? dim('n/a') : fmtNum(targetHits),
      sourceOnly ? STATUS.INFO : targetHits === 0 ? STATUS.PASS : STATUS.FAIL,
      sourceOnly ? 'expected before step 04' : targetHits === 0 ? '' : 'step 04 did not rewrite these'
    );
  }
  for (const [collection, hits] of [...sourceRef.perCollection.entries()].sort()) {
    const targetHits = targetRef.perCollection.get(collection) || 0;
    addRow(
      refCategory,
      `kv_collections/${collection} — old ref`,
      fmtNum(hits),
      sourceOnly ? dim('n/a') : fmtNum(targetHits),
      sourceOnly ? STATUS.INFO : targetHits === 0 ? STATUS.PASS : STATUS.FAIL,
      sourceOnly ? '' : targetHits === 0 ? '' : 'rewrite these URLs before cutover'
    );
  }
  addRow(
    refCategory,
    'TOTAL rows holding the OLD ref',
    fmtNum(sourceRef.total),
    sourceOnly ? dim('n/a') : fmtNum(targetRef.total),
    sourceOnly ? STATUS.INFO : targetRef.total === 0 ? STATUS.PASS : STATUS.FAIL,
    sourceOnly ? '' : targetRef.total === 0 ? '' : 'must be 0 after step 04'
  );
  if (sourceRef.total === 0) {
    addRow(
      refCategory,
      'old ref found anywhere on the SOURCE',
      fmtNum(0),
      sourceOnly ? dim('n/a') : fmtNum(targetRef.total),
      STATUS.WARN,
      `the source holds no "${options.oldRef}" URL at all — this kit expects ~43 (pricelist.image + form_templates.cover_image). Wrong --old-ref?`
    );
  }

  /**
   * The other half of the check. "Old ref gone" is also true if step 04 blanked
   * the URLs, or if kv_collections restored empty. Every row that carried the
   * old ref on the source must carry the new ref on the target.
   */
  if (sourceOnly) {
    addRow(
      refCategory,
      'rows holding the NEW ref',
      dim('n/a'),
      dim('n/a'),
      STATUS.INFO,
      'nothing to compare on a source-only run'
    );
  } else if (!targetRef.newScanned) {
    addRow(
      refCategory,
      'rows holding the NEW ref',
      dim('—'),
      red('not scanned'),
      STATUS.FAIL,
      'no new project ref was resolved — pass --new-ref, or use a postgres.<ref> pooler URL'
    );
  } else {
    for (const [collection, hits] of [...sourceRef.perCollection.entries()].sort()) {
      const gained = targetRef.perCollectionNew.get(collection) || 0;
      addRow(
        refCategory,
        `kv_collections/${collection} — new ref`,
        fmtNum(hits),
        fmtNum(gained),
        gained >= hits ? STATUS.PASS : STATUS.FAIL,
        gained >= hits
          ? ''
          : `${fmtNum(hits - gained)} row(s) lost their URL instead of being rewritten`
      );
    }
    addRow(
      refCategory,
      'TOTAL rows holding the NEW ref',
      fmtNum(sourceRef.total),
      fmtNum(targetRef.totalNew),
      targetRef.totalNew !== null && sourceRef.total !== null && targetRef.totalNew >= sourceRef.total
        ? STATUS.PASS
        : STATUS.FAIL,
      targetRef.totalNew !== null && sourceRef.total !== null && targetRef.totalNew >= sourceRef.total
        ? 'every row that carried the old ref now carries the new one'
        : 'fewer rows carry the new ref than carried the old one — the rewrite dropped URLs'
    );
  }

  // ── 9. SECURITY DEFINER functions ─────────────────────────────────────────
  const functionCategory = report.category('9. SECURITY DEFINER functions and the evidence trigger');
  const sourceFunctions = source.functions || emptyMap;
  const targetFunctions = tgt.functions || emptyMap;
  const sourceSecdef = [...sourceFunctions.entries()]
    .filter(([, value]) => value.securityDefiner)
    .map(([key]) => key);
  const expectedFunctions = [...new Set([...REQUIRED_SECDEF_FUNCTIONS, ...sourceSecdef])].sort();

  for (const signature of expectedFunctions) {
    const inSource = sourceFunctions.has(signature);
    const inTarget = targetFunctions.has(signature);
    const sourceLabel = inSource
      ? sourceFunctions.get(signature).securityDefiner
        ? green('definer')
        : yellow('invoker')
      : red('missing');
    if (sourceOnly) {
      const definerOnSource = inSource && sourceFunctions.get(signature).securityDefiner === true;
      addRow(
        functionCategory,
        signature,
        sourceLabel,
        dim('n/a'),
        definerOnSource ? STATUS.INFO : STATUS.WARN,
        inSource
          ? 'exists but is SECURITY INVOKER — the API role must own the privilege'
          : 'declared by database/*.sql but not present in production'
      );
      continue;
    }
    const targetLabel = inTarget
      ? targetFunctions.get(signature).securityDefiner
        ? green('definer')
        : yellow('invoker')
      : red('missing');
    const ok = inTarget && targetFunctions.get(signature).securityDefiner === true;

    // Absent on BOTH sides is not a restore defect. Several of these live in
    // migrations the owner may never have applied (20260813_registration_
    // lifecycle.sql says so in its own header), and this gate exists to catch
    // what the move broke, not to re-litigate production's current state.
    // server/supa.js calls them via .rpc(), so it is still worth a WARN.
    if (!inSource && !inTarget) {
      addRow(
        functionCategory,
        signature,
        sourceLabel,
        targetLabel,
        STATUS.WARN,
        'absent on BOTH sides — the migration that creates it was never applied; supa.js .rpc() calls it'
      );
      continue;
    }
    addRow(
      functionCategory,
      signature,
      sourceLabel,
      targetLabel,
      ok ? STATUS.PASS : STATUS.FAIL,
      ok ? '' : inTarget ? 'lost SECURITY DEFINER in the restore' : 'present on the source, NOT restored'
    );
  }

  // Same regression rule as the functions above: lost in the restore is a FAIL,
  // never applied to production in the first place is a WARN.
  const triggerOnSource = source.appendOnlyTrigger === true;
  const triggerOnTarget = tgt.appendOnlyTrigger === true;
  const triggerStatus = sourceOnly
    ? triggerOnSource
      ? STATUS.PASS
      : STATUS.WARN
    : triggerOnTarget
      ? STATUS.PASS
      : triggerOnSource
        ? STATUS.FAIL
        : STATUS.WARN;
  addRow(
    functionCategory,
    `trigger ${APPEND_ONLY_TRIGGER.name} on ${APPEND_ONLY_TRIGGER.table}`,
    triggerOnSource ? green('present') : red('missing'),
    sourceOnly ? dim('n/a') : triggerOnTarget ? green('present') : red('missing'),
    triggerStatus,
    triggerStatus === STATUS.PASS
      ? ''
      : triggerOnSource
        ? 'LOST in the restore — the signature-evidence journal is no longer append-only'
        : 'absent on both sides — 20260805_signature_evidence.sql was never applied'
  );

  // ── 10. RLS and public-role grants, judged as a REGRESSION ────────────────
  //
  // The earlier draft of this category judged the target in absolute terms: any
  // table without RLS, any anon SELECT grant, any PUBLIC EXECUTE on a SECURITY
  // DEFINER function was a FAIL. Run against this repo that is a gate nobody
  // can ever pass — pg_proc.proacl is NULL for a freshly created function, so
  // acldefault() correctly reports "PUBLIC has EXECUTE" on the source too, and
  // a gate that fails on a perfect restore just teaches the operator to skip it.
  //
  // So: worse than the source is a FAIL, equal to the source is a WARN with the
  // hole named. That still catches the thing this step exists to catch — a new
  // Supabase project ships ALTER DEFAULT PRIVILEGES granting anon/authenticated
  // on the public schema, so a restore frequently re-opens exactly what
  // database/20260814_enforce_api_only_access.sql revoked.
  const judged = sourceOnly ? source : tgt;
  const securityCategory = report.category(
    '10. RLS and public-role grants',
    sourceOnly
      ? 'source posture, recorded as a baseline'
      : 'FAIL = the restore made it worse than the source; WARN = pre-existing, fix separately'
  );

  const sourceRls = new Map((source.publicTables || []).map((table) => [table.name, table]));
  const judgedRls = new Map((judged.publicTables || []).map((table) => [table.name, table]));
  for (const name of [...judgedRls.keys()].sort()) {
    if (RLS_EXEMPT_TABLES.has(name)) continue;
    const judgedTable = judgedRls.get(name);
    const sourceTable = sourceRls.get(name);
    const onTarget = judgedTable.rlsEnabled === true;
    // A table that only exists on the target has no source posture to regress
    // from; hold it to the absolute rule instead.
    const onSource = sourceTable ? sourceTable.rlsEnabled === true : true;
    const status = onTarget ? STATUS.PASS : onSource ? STATUS.FAIL : STATUS.WARN;
    if (sourceOnly && status === STATUS.PASS) continue;
    addRow(
      securityCategory,
      `RLS ${name}`,
      sourceTable ? (sourceTable.rlsEnabled ? green('on') : red('OFF')) : dim('absent'),
      sourceOnly ? dim('n/a') : judgedTable.rlsEnabled ? green('on') : red('OFF'),
      status,
      status === STATUS.PASS
        ? ''
        : status === STATUS.FAIL
          ? 'RLS was ON at the source and is OFF here — the restore dropped it'
          : 'RLS is off on both sides (pre-existing) — ALTER TABLE ... ENABLE ROW LEVEL SECURITY'
    );
  }
  if (!judgedRls.size) {
    addRow(securityCategory, 'RLS inventory', dim('—'), red('no tables read'), STATUS.FAIL, 'could not read pg_class');
  } else {
    addRow(
      securityCategory,
      'tables with RLS enabled',
      fmtNum([...sourceRls.values()].filter((table) => table.rlsEnabled).length),
      sourceOnly
        ? dim('n/a')
        : fmtNum([...judgedRls.values()].filter((table) => table.rlsEnabled).length),
      STATUS.PASS,
      `of ${fmtNum(judgedRls.size)} public tables`
    );
  }

  /**
   * One comparison shape for all three grant checks: count the offending grants
   * on each side, FAIL when the target has more, WARN when it merely matches a
   * non-zero source.
   */
  const grantCheck = (label, rows, pick, describe, explainClean) => {
    const sourceHits = (source[rows] || []).filter(pick);
    const judgedHits = (judged[rows] || []).filter(pick);
    const status = sourceOnly
      ? judgedHits.length === 0
        ? STATUS.PASS
        : STATUS.WARN
      : judgedHits.length > sourceHits.length
        ? STATUS.FAIL
        : judgedHits.length === 0
          ? STATUS.PASS
          : STATUS.WARN;
    addRow(
      securityCategory,
      label,
      fmtNum(sourceHits.length),
      sourceOnly ? dim('n/a') : fmtNum(judgedHits.length),
      status,
      status === STATUS.PASS
        ? explainClean
        : `${status === STATUS.FAIL ? 'NEW on the target: ' : 'pre-existing on both sides: '}${describe(
            judgedHits
          )}`
    );
  };

  grantCheck(
    'write grants to anon / PUBLIC / authenticated',
    'tableGrants',
    (grant) => PUBLIC_ROLES.includes(grant.grantee) && WRITE_PRIVILEGES.has(grant.privilege),
    (hits) =>
      hits
        .slice(0, 4)
        .map((grant) => `${grant.grantee}:${grant.privilege} on ${grant.name}`)
        .join(', '),
    'the API is the only write path'
  );
  grantCheck(
    'SELECT grants to anon / PUBLIC / authenticated',
    'tableGrants',
    (grant) => PUBLIC_ROLES.includes(grant.grantee) && grant.privilege === 'SELECT',
    (hits) =>
      `CRM rows readable through PostgREST: ${[...new Set(hits.map((grant) => grant.name))]
        .slice(0, 4)
        .join(', ')}`,
    ''
  );
  grantCheck(
    'EXECUTE on SECURITY DEFINER functions by public roles',
    'functionGrants',
    (grant) =>
      grant.securityDefiner && PUBLIC_ROLES.includes(grant.grantee) && grant.privilege === 'EXECUTE',
    (hits) =>
      hits
        .slice(0, 3)
        .map((grant) => `${grant.grantee} -> ${grant.signature}`)
        .join(', '),
    ''
  );

  return { report };
}

// ─── main ───────────────────────────────────────────────────────────────────

async function main() {
  let options;
  try {
    options = parseArgs(process.argv.slice(2));
  } catch (error) {
    console.error(red(`Argument error: ${error.message}`));
    console.error(HELP);
    return 2;
  }
  if (options.help) {
    console.log(HELP);
    return 0;
  }

  const nodeMajor = Number(process.versions.node.split('.')[0]);
  if (nodeMajor < 20) {
    console.error(red(`Node 20+ required, running ${process.versions.node}`));
    return 2;
  }

  console.log(bold('migration/05-verify.mjs — READ-ONLY verification'));
  console.log(
    dim('No INSERT/UPDATE/DELETE/DDL/storage write exists in this script; every session is')
  );
  console.log(dim('additionally set to TRANSACTION READ ONLY, so PostgreSQL rejects writes too.'));
  console.log('');

  // Config
  let inventory;
  try {
    inventory = loadTableInventory();
  } catch (error) {
    console.error(red(`Cannot read the table inventory: ${error.message}`));
    return 2;
  }

  let envValues = {};
  let envPath = '';
  try {
    envPath = resolveEnvFile(options.envFile);
    if (envPath) envValues = readEnvFile(envPath);
  } catch (error) {
    console.error(red(`Cannot read the env file: ${error.message}`));
    return 2;
  }

  let targetEnvValues = {};
  let targetEnvPath = options.targetEnvFile || path.join(REPO_ROOT, 'migration', '.env.target');
  if (fs.existsSync(targetEnvPath)) {
    try {
      targetEnvValues = readEnvFile(targetEnvPath);
    } catch (error) {
      console.error(red(`Cannot read the target env file: ${error.message}`));
      return 2;
    }
  } else if (options.targetEnvFile) {
    console.error(red(`Target env file not found: ${targetEnvPath}`));
    return 2;
  } else {
    targetEnvPath = '';
  }

  // The rest of the kit passes the old ref as OLD_REF; honour it here too.
  if (!options.oldRefExplicit) {
    options.oldRef =
      process.env.OLD_REF || envValues.OLD_REF || targetEnvValues.OLD_REF || options.oldRef;
  }

  const sourceUrl =
    options.sourceUrl ||
    process.env.SOURCE_DATABASE_URL ||
    envValues.SOURCE_DATABASE_URL ||
    process.env.DATABASE_URL ||
    envValues.DATABASE_URL ||
    '';
  const targetUrl =
    options.targetUrl ||
    process.env.TARGET_DATABASE_URL ||
    targetEnvValues.TARGET_DATABASE_URL ||
    targetEnvValues.DATABASE_URL ||
    envValues.TARGET_DATABASE_URL ||
    '';

  if (!sourceUrl) {
    console.error(red('No SOURCE connection string.'));
    console.error('  Pass --source-url, or set DATABASE_URL in server/.env.');
    return 2;
  }
  if (!targetUrl && !options.sourceOnly) {
    console.error(red('No TARGET connection string.'));
    console.error('  Pass --target-url, set TARGET_DATABASE_URL, or write migration/.env.target.');
    console.error('  To take a pre-migration baseline of the source alone, use --source-only.');
    return 2;
  }

  const sourceRef = projectRefOf(sourceUrl);
  const targetRef = projectRefOf(targetUrl);
  if (!options.sourceOnly && sourceRef && targetRef && sourceRef === targetRef) {
    console.error(red(`SOURCE and TARGET point at the same project ref (${sourceRef}).`));
    console.error('  Everything would trivially "match". Refusing to run.');
    return 2;
  }
  if (!options.sourceOnly && targetRef && targetRef === options.oldRef) {
    console.error(red(`TARGET points at the OLD project ref (${options.oldRef}). Refusing to run.`));
    return 2;
  }
  if (!options.sourceOnly && (!sourceRef || !targetRef)) {
    // Without both refs the two guards above are silently inert, and the
    // new-ref half of category 8 cannot run. Say so rather than pretend.
    console.log(
      yellow(
        'Note: a connection string is not of the form postgresql://postgres.<ref>:<pw>@host/db,' +
          ' so SOURCE/TARGET could not be told apart automatically. Pass --new-ref explicitly.'
      )
    );
  }
  if (sourceRef && sourceRef !== options.oldRef) {
    console.log(
      yellow(
        `Note: the source project ref is "${sourceRef}" but the ref being scanned for is "${options.oldRef}". Pass --old-ref if that is wrong.`
      )
    );
  }

  // The rest of the kit derives the old ref from SUPABASE_URL (see
  // 04-rewrite-urls.mjs). Disagreement here means server/.env has already been
  // flipped to the new project, and scanning for the wrong ref would report a
  // reassuring zero. Warn; do not silently adopt it.
  const envRef = refFromSupabaseUrl(envValues.SUPABASE_URL || process.env.SUPABASE_URL || '');
  if (envRef && envRef !== options.oldRef) {
    console.log(
      yellow(
        `Note: SUPABASE_URL in the env file points at "${envRef}", not the ref being scanned for ("${options.oldRef}").`
      )
    );
  }

  options.newRef = options.newRef || (options.sourceOnly ? '' : targetRef);
  if (!options.sourceOnly && !options.newRef) {
    console.log(
      yellow('Note: no new project ref resolved — the "new ref arrived" half of category 8 will FAIL.')
    );
  }
  if (options.newRef && options.newRef === options.oldRef) {
    console.error(red('--new-ref and --old-ref are the same value. Refusing to run.'));
    return 2;
  }

  for (const [label, url] of [['SOURCE', sourceUrl], ['TARGET', targetUrl]]) {
    if (!url) continue;
    let port = '';
    try {
      port = new URL(url).port || SESSION_POOLER_PORT;
    } catch {
      port = '';
    }
    if (port && port !== SESSION_POOLER_PORT && /pooler\.supabase\.com$/i.test(hostOf(url))) {
      console.log(
        yellow(
          `Note: ${label} uses the pooler on :${port}. Only the SESSION pooler (:${SESSION_POOLER_PORT}) keeps` +
            ' `SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY`; the connection guard will refuse to continue.'
        )
      );
    }
  }

  console.log(`  inventory     ${dim(inventory.supaPath)}`);
  console.log(
    `                ${fmtNum(inventory.direct.length)} direct tables, ${fmtNum(
      inventory.operational.length
    )} kv collections`
  );
  console.log(`  env file      ${dim(envPath || '(none — using process env only)')}`);
  if (targetEnvPath) console.log(`  target env    ${dim(targetEnvPath)}`);
  console.log(`  SOURCE        ${describeConnection(sourceUrl)}`);
  console.log(
    `  TARGET        ${options.sourceOnly ? dim('(source-only run — NOT a cutover gate)') : describeConnection(targetUrl)}`
  );
  console.log(`  old ref       ${options.oldRef}`);
  console.log(`  new ref       ${options.newRef || dim('(none resolved)')}`);
  console.log(
    `  tls           ${options.noSsl ? 'disabled' : options.strictSsl ? 'verified chain' : 'encrypted, chain not verified (--strict-ssl to verify)'}`
  );

  let pg;
  try {
    pg = loadPgModule();
  } catch (error) {
    console.error(red(error.message));
    return 2;
  }

  const sourceConn = new ReadOnlyConnection('SOURCE', sourceUrl, options, pg);
  const targetConn = options.sourceOnly
    ? null
    : new ReadOnlyConnection('TARGET', targetUrl, options, pg);

  let sourceSnapshot = null;
  let targetSnapshot = null;
  try {
    console.log('');
    console.log('Connecting (read-only sessions)...');
    await sourceConn.connect();
    if (targetConn) await targetConn.connect();

    console.log('Reading SOURCE...');
    console.log(
      dim('  (the project-ref scan casts every row of every public table to text — minutes, not seconds)')
    );
    sourceSnapshot = await snapshot(sourceConn, inventory, options.oldRef, options.newRef);
    console.log(`  ${describeConnection(sourceUrl)} — ${sourceSnapshot.version}`);
    if (targetConn) {
      console.log('Reading TARGET...');
      targetSnapshot = await snapshot(targetConn, inventory, options.oldRef, options.newRef);
      console.log(`  ${describeConnection(targetUrl)} — ${targetSnapshot.version}`);
    }
  } catch (error) {
    console.error('');
    console.error(red(`Verification could not run: ${error.message}`));
    console.error(
      dim(
        '  Use the SESSION-mode pooler (aws-1-<region>.pooler.supabase.com:5432, user postgres.<ref>).'
      )
    );
    console.error(dim('  The direct db.<ref>.supabase.co host is IPv6-only.'));
    await sourceConn.end();
    if (targetConn) await targetConn.end();
    return 2;
  }

  await sourceConn.end();
  if (targetConn) await targetConn.end();

  const { report } = buildReport(options, inventory, sourceSnapshot, targetSnapshot);
  report.print();

  console.log('');
  console.log(bold('SUMMARY'));
  renderTable(
    ['CATEGORY', 'RESULT', 'DETAIL'],
    report.categories.map((category) => [
      `  ${category.title}`,
      paintStatus(categoryStatus(category)),
      dim(
        categoryStatus(category) === STATUS.PASS || categoryStatus(category) === STATUS.INFO
          ? `${category.rows.length} checks`
          : `${category.failures} failed / ${category.warnings} warnings of ${category.rows.length}`
      ),
    ]),
    ['l', 'l', 'l']
  );

  const queriesRun = sourceConn.queryCount + (targetConn ? targetConn.queryCount : 0);
  console.log('');
  console.log(dim(`${queriesRun} read-only statements were sent. Nothing was written.`));

  if (options.jsonPath) {
    // The only write this script performs, and only when asked for. It holds
    // counts and password-stripped connection descriptions — never a secret.
    const serialisable = {
      generatedAt: new Date().toISOString(),
      oldRef: options.oldRef,
      newRef: options.newRef || null,
      sourceOnly: options.sourceOnly,
      source: describeConnection(sourceUrl),
      target: options.sourceOnly ? null : describeConnection(targetUrl),
      verdict: options.sourceOnly ? 'BASELINE' : report.failed ? 'FAIL' : 'PASS',
      categories: report.categories.map((category) => ({
        title: category.title,
        status: categoryStatus(category),
        failures: category.failures,
        warnings: category.warnings,
        rows: category.rows.map((row) => ({
          check: row.check,
          source: String(row.source).replace(/\[[0-9;]*m/g, ''),
          target: String(row.target).replace(/\[[0-9;]*m/g, ''),
          status: row.status,
          note: row.note,
        })),
      })),
    };
    try {
      fs.mkdirSync(path.dirname(path.resolve(options.jsonPath)), { recursive: true });
      fs.writeFileSync(options.jsonPath, `${JSON.stringify(serialisable, null, 2)}\n`, 'utf8');
      console.log(dim(`report written to ${path.resolve(options.jsonPath)}`));
    } catch (error) {
      console.error(yellow(`Could not write the --json report: ${error.message}`));
    }
  }

  /**
   * Printed on every outcome, not only on PASS. Both of these are invisible
   * from inside the two databases, and each one silently corrupts live data if
   * it is missed — exactly the kind of thing a green wall of PASS hides.
   */
  const printBlindSpots = () => {
    console.log('');
    console.log(bold('NOT CHECKED HERE — confirm by hand before cutover:'));
    console.log('  1. EVIDENCE_SIGNING_SECRET on Render = the OLD project service_role key.');
    console.log(
      dim('     signatureEvidence.js / otpService.js / mailingPreferences.js derive their HMAC key')
    );
    console.log(
      dim('     from EVIDENCE_SIGNING_SECRET || OTP_TOKEN_SECRET || SUPABASE_SERVICE_ROLE_KEY, and')
    );
    console.log(
      dim('     neither dedicated secret is set — so the key IS the service_role key today. A new')
    );
    console.log(
      dim('     project regenerates it and every sealed declaration, waiver and unsubscribe link dies.')
    );
    console.log('  2. Rebuild and redeploy the Vercel client in the same window.');
    console.log(dim('     VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY are inlined at BUILD time.'));
  };

  console.log('');
  if (options.sourceOnly) {
    console.log(
      yellow('VERDICT: BASELINE ONLY — no target was compared. This run is NOT a cutover gate.')
    );
    printBlindSpots();
    return report.failed ? 1 : 0;
  }
  if (report.failed) {
    const failed = report.categories.filter((category) => categoryStatus(category) === STATUS.FAIL);
    console.log(
      red(
        `VERDICT: FAIL — ${failed.length} categor${failed.length === 1 ? 'y' : 'ies'} did not match. DO NOT CUT OVER.`
      )
    );
    for (const category of failed) console.log(red(`  - ${category.title}`));
    printBlindSpots();
    return 1;
  }
  console.log(green('VERDICT: PASS — target matches source on every checked category.'));
  const warned = report.categories.filter((category) => categoryStatus(category) === STATUS.WARN);
  if (warned.length) {
    console.log(
      yellow(
        `  ${warned.length} categor${warned.length === 1 ? 'y carries' : 'ies carry'} warnings — WARN does not gate, but read them:`
      )
    );
    for (const category of warned) console.log(yellow(`  - ${category.title}`));
  }
  printBlindSpots();
  return 0;
}

/**
 * Run when executed, stay quiet when imported (the comparison logic has its own
 * harness). Anything other than a plain `import` of this file runs main().
 */
const invokedDirectly = (() => {
  const entry = process.argv[1] ? path.resolve(process.argv[1]) : '';
  if (!entry) return true;
  const self = fileURLToPath(import.meta.url);
  return process.platform === 'win32'
    ? entry.toLowerCase() === self.toLowerCase()
    : entry === self;
})();

if (invokedDirectly) {
  main()
    .then((code) => {
      process.exitCode = code;
    })
    .catch((error) => {
      console.error(red(`Unexpected failure: ${error?.stack || error}`));
      process.exitCode = 2;
    });
}
