-- Durable sales workflow fields and lead-funnel status tracking.

ALTER TABLE public.parents
  ADD COLUMN IF NOT EXISTS next_followup date;

CREATE TABLE IF NOT EXISTS public.lead_status_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type text NOT NULL CHECK (entity_type IN ('parent', 'student')),
  entity_id text NOT NULL,
  parent_id text NOT NULL,
  from_status text,
  to_status text,
  source text NOT NULL DEFAULT 'database_trigger',
  changed_at timestamptz NOT NULL DEFAULT now(),
  is_baseline boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS lead_status_history_parent_changed_idx
  ON public.lead_status_history (parent_id, changed_at);
CREATE INDEX IF NOT EXISTS lead_status_history_conversion_idx
  ON public.lead_status_history (is_baseline, to_status, changed_at);
CREATE UNIQUE INDEX IF NOT EXISTS lead_status_history_one_baseline_per_entity_idx
  ON public.lead_status_history (entity_type, entity_id)
  WHERE is_baseline;

-- Existing records establish the state at tracking start. They are context only,
-- never conversion events.
INSERT INTO public.lead_status_history (
  entity_type,
  entity_id,
  parent_id,
  from_status,
  to_status,
  source,
  is_baseline
)
SELECT
  'parent',
  p.id,
  p.id,
  NULL,
  COALESCE(NULLIF(p.status, ''), 'lead_new'),
  'migration_baseline',
  true
FROM public.parents p
ON CONFLICT (entity_type, entity_id) WHERE is_baseline DO NOTHING;

INSERT INTO public.lead_status_history (
  entity_type,
  entity_id,
  parent_id,
  from_status,
  to_status,
  source,
  is_baseline
)
SELECT
  'student',
  s.id,
  s.parent_id,
  NULL,
  COALESCE(NULLIF(s.status, ''), 'lead_new'),
  'migration_baseline',
  true
FROM public.students s
WHERE s.parent_id IS NOT NULL
ON CONFLICT (entity_type, entity_id) WHERE is_baseline DO NOTHING;

CREATE OR REPLACE FUNCTION public.record_lead_status_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  new_row jsonb;
  resolved_parent_id text;
  old_status text;
  new_status text;
  event_source text;
BEGIN
  new_row := to_jsonb(NEW);
  resolved_parent_id := CASE
    WHEN TG_TABLE_NAME = 'parents' THEN new_row ->> 'id'
    ELSE new_row ->> 'parent_id'
  END;
  old_status := CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE NULLIF(OLD.status, '') END;
  new_status := CASE
    WHEN TG_OP = 'INSERT' THEN COALESCE(NULLIF(NEW.status, ''), 'lead_new')
    ELSE NULLIF(NEW.status, '')
  END;
  event_source := COALESCE(
    NULLIF(current_setting('app.lead_status_source', true), ''),
    'database_trigger'
  );

  IF resolved_parent_id IS NULL THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' OR old_status IS DISTINCT FROM new_status THEN
    INSERT INTO public.lead_status_history (
      entity_type,
      entity_id,
      parent_id,
      from_status,
      to_status,
      source,
      is_baseline
    )
    VALUES (
      CASE WHEN TG_TABLE_NAME = 'parents' THEN 'parent' ELSE 'student' END,
      NEW.id,
      resolved_parent_id,
      old_status,
      new_status,
      event_source,
      false
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS parents_lead_status_history ON public.parents;
CREATE TRIGGER parents_lead_status_history
AFTER INSERT OR UPDATE OF status ON public.parents
FOR EACH ROW
EXECUTE FUNCTION public.record_lead_status_change();

DROP TRIGGER IF EXISTS students_lead_status_history ON public.students;
CREATE TRIGGER students_lead_status_history
AFTER INSERT OR UPDATE OF status ON public.students
FOR EACH ROW
EXECUTE FUNCTION public.record_lead_status_change();

ALTER TABLE public.lead_status_history ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.lead_status_history FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.lead_status_history_id_seq FROM anon, authenticated;
GRANT ALL ON TABLE public.lead_status_history TO postgres, service_role;
GRANT ALL ON SEQUENCE public.lead_status_history_id_seq TO postgres, service_role;
